/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.0.0/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "logitrack"

include(
    "common:common-core",
    "common:common-security",
    "common:common-kafka",
    "common:common-test",
    "gateway-service",
    "auth-service",
    "shipment-service",
    "inventory-service",
    "carrier-service",
    "tracking-service",
    "billing-service",
    "notification-service",
    "analytics-service"
)
